version: "2"

linters:
  enable:
    - unused
    - revive
    - gocritic
    - errorlint
    - nolintlint
    - misspell
    - gochecknoglobals
    - gochecknoinits
    - exhaustive
    - gocognit
    - nestif
    - funlen
    - decorder
    - embeddedstructfieldcheck
    - recvcheck
    - interfacebloat
    - cyclop
    - gofmt
    - gofumpt
    - goimports

  settings:
    gocognit:
      min-complexity: 15
    nestif:
      min-complexity: 4
    cyclop:
      max-complexity: 15
      package-average: 10.0

  exclusions:
    rules:
      - path: (^|.*/)config\.go$
        linters:
          - revive
        text: "don't use ALL_CAPS in Go names; use CamelCase"
