version: "2"

linters:
  enable:
    - unused
    - revive
    - gocritic
    - errorlint
    - nolintlint
    - misspell
    - gochecknoglobals
    - gochecknoinits
    - exhaustive
    - gocognit
    - nestif
    - funlen

  settings:
    gocognit:
      min-complexity: 15
    nestif:
      min-complexity: 4

  exclusions:
    rules:
      - path: (^|.*/)config\.go$
        linters:
          - revive
        text: "don't use ALL_CAPS in Go names; use CamelCase"
